name: 'Docker Login'
inputs:
  username:
    required: true
  password:
    required: true
  login-server:
    required: true
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'